AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: bpartners-annotator - Computation and API

Globals:
  Function:
    CodeUri: .
    Runtime: java21
    Tracing: Active
    Architectures:
      - arm64
    EventInvokeConfig:
      MaximumRetryAttempts: 0
    AutoPublishAlias: live
    SnapStart:
      ApplyOn: PublishedVersions
    VpcConfig:
      SecurityGroupIds:
        - !Sub '{{resolve:ssm:/bpartners-imagery/sg/id}}'
      SubnetIds:
        - !Sub '{{resolve:ssm:/bpartners-imagery/private/subnet1/id}}'
        - !Sub '{{resolve:ssm:/bpartners-imagery/private/subnet2/id}}'
    Environment:
      Variables:
        ENV: !Ref Env
        AWS_S3_BUCKET: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/s3/bucket-name}}'
        AWS_SES_SOURCE: contact@bpartners.app
        AWS_EVENTBRIDGE_BUS: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/eventbridge/bus-name}}'
        AWS_EVENT_STACK_1_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/1/sqs/mailbox-queue-url}}'
        AWS_EVENT_STACK_2_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/2/sqs/mailbox-queue-url}}'
        
        
        ADMIN_API_KEY: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/admin/api-key}}'
        GEO_JOBS_API_KEY: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/geojobs/api-key}}'
        GEO_JOBS_API_URL: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/geojobs/api-url}}'
        AWS_COGNITO_USERPOOL_ID: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/cognito/userpool-id}}'
        AWS_COGNITO_USERPOOL_DOMAIN: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/cognito/userpool-domain}}'
        AWS_COGNITO_USERPOOL_CLIENTID: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/cognito/userpool-client-id}}'
        AWS_COGNITO_USERPOOL_CLIENTSECRET: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/cognito/userpool-client-secret}}'
        GEOJOBS_USER_INFO: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/geojobs/userinfo}}'
        TASKS_INSERT_LIMIT_MAX: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/max-tasks-insert-nb}}'
        SPRING_DATASOURCE_URL: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/neon/db/url}}'
        SPRING_DATASOURCE_USERNAME: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/neon/db/username}}'
        SPRING_DATASOURCE_PASSWORD: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/neon/db/password}}'
        

Parameters:
  Env:
    Type: String

Resources:
  FrontalServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - "*~1*"

  FrontalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.bpartners.annotator.ApiEventHandler::handleRequest
      MemorySize: 512
      Timeout: 300
      Role: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/execution/role-arn}}'
      
      Events:
        ApiCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: FrontalServerlessRestApi

  WorkerFunction1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.bpartners.annotator.MailboxEventHandler::handleRequest
      MemorySize: 512
      Timeout: 600 #note(sqs-visibility)
      Role: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/execution/role-arn}}'
      
      Events:
        AllEvents:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/1/sqs/mailbox-queue-arn}}'
            BatchSize: 1

  WorkerFunction2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.bpartners.annotator.MailboxEventHandler::handleRequest
      MemorySize: 512
      Timeout: 600 #note(sqs-visibility)
      Role: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/execution/role-arn}}'
      
      Events:
        AllEvents:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/2/sqs/mailbox-queue-arn}}'
            BatchSize: 1

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

  ApiUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /bpartners-annotator/, !Ref Env, /api/url ] ]
      Type: String
      Value: !Sub "https://${FrontalServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !GetAtt ApiUrlSSM.Value
